# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Study\Proprioceptive Actuator\iPyTTCANOpen\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self, *args, **kwargs):
        super(Ui_MainWindow, self).__init__(*args, **kwargs)

    def setupUi(self):
        self.resize(1116, 532)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.setCentralWidget(self.centralwidget)
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_serial = QtWidgets.QLabel(self.centralwidget)
        self.label_serial.setObjectName("label_serial")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_serial)
        self.serialSelector = QtWidgets.QComboBox(self.centralwidget)
        self.serialSelector.setObjectName("serialSelector")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.serialSelector)
        self.label_position = QtWidgets.QLabel(self.centralwidget)
        self.label_position.setObjectName("label_position")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_position)
        self.positionSlider = QtWidgets.QSlider(self.centralwidget)
        self.positionSlider.setMaximum(6283)
        self.positionSlider.setPageStep(10)
        self.positionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.positionSlider.setObjectName("positionSlider")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.positionSlider)
        self.label_kpkd = QtWidgets.QLabel(self.centralwidget)
        self.label_kpkd.setObjectName("label_kpkd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_kpkd)
        self.kpkd_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.kpkd_lineEdit.setObjectName("kpkd_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.kpkd_lineEdit)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_3)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 24))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_serial.setText(_translate("MainWindow", "Serial port"))
        self.label_position.setText(_translate("MainWindow", "Position"))
        self.label_kpkd.setText(_translate("MainWindow", "Kp,Kd:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow()
    ui.setupUi()
    ui.show()
    sys.exit(app.exec_())
